# Generated by Django 4.2.1 on 2023-05-20 03:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_rename_news_newss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newss',
            new_name='News',
        ),
    ]
