"use client"
import './globals.css'
import Header from '@/component/Header'


export const metadata = {
  title: 'News Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}</body>
    </html>
  )
}
